### ISSUE TITLE
SQL error while attempting to connect.

### ISSUE THREAD

**Issue by avarishd** [stoneharry/WoW-Spell-Editor#140]
**Spell editor version**
1.9.8

**Describe the bug**
After attempting to connect to sql (details are correct) I am met with the following bug.

**To Reproduce**
Attempt to connect to sql.

**Expected behavior**
Should connect to my msql database and bind all the tables

System: Win10

**Screenshots**
![e90716e4c3941a158ec3593e0b8bc2d7](https://user-images.githubusercontent.com/46330494/131879935-ba76d41c-7fa4-409d-b361-8a0d9c65420d.png)

Debug log:

[19:13:09.4743|ERROR|SpellEditor.MainWindow] ERROR: A call to SSPI failed, see inner exception.
The function requested is not supported
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at MySql.Data.MySqlClient.NativeDriver.StartSSL()
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SpellEditor.Sources.Database.MySQL..ctor()
   at SpellEditor.MainWindow.<>c__DisplayClass44_0.<loadAllData>b__0()

**Comment by stoneharry** [comment]
Looks like an issue with the MySQL connector library: https://github.com/mysql-net/MySqlConnector/issues/428

Looks like it might be because of TLS 1.2.

**Comment by stoneharry** [comment]
f81c514d277f959bcd926e95047458fefd7994a2 Might fix this.

**Comment by stoneharry** [comment]
This might be fixed in release build 2.0, are you able to retest this please?

**Comment by stoneharry** [comment]
Closing as fixed. If this occurs in the future we can open a new issue.
