### ISSUE TITLE
Cannot get Mariadb database object

### ISSUE THREAD

**Issue by a-l-le** [stoneharry/WoW-Spell-Editor#230]
**Spell editor version**
v2.2.1

**Describe the bug**
After setting up db connection details the program cannot get a db object

**To Reproduce**
Choose mysql connection on startup

**Expected behavior**

**Screenshots**

**Additional context**
`[17:26:32.3058|INFO|SpellEditor.MainWindow] ######################################################
[17:26:32.3558|INFO|SpellEditor.MainWindow] Starting WoW Spell Editor - 24-Mar-24 5:26:32 PM
[17:26:32.3558|INFO|SpellEditor.MainWindow] ######################################################
[17:26:35.9848|ERROR|SpellEditor.MainWindow] ERROR: Object cannot be cast from DBNull to other types.

System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SpellEditor.Sources.Database.MySQL..ctor(Boolean initialiseDatabase)
   at SpellEditor.Sources.Database.AdapterFactory.GetAdapter(Boolean initialiseDatabase)
   at SpellEditor.MainWindow.<>c__DisplayClass44_0.<loadAllData>b__0()`

Not a connection/authorization issue as it throws different errors when I try to replicate one. I've tried different versions from 1.0.x to 2.2.1 same result. Haven't tried a mysql server because I don't have one.

**Comment by stoneharry** [comment]
What version of MariaDB are you using?

**Comment by a-l-le** [comment]
Sorry forgot to mention
mariadb  Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64)

**Comment by dremcon** [comment]
I have the same issue with the same debug error output. Also running on mariadb V 15.1 on debian-linux.

**Comment by stoneharry** [comment]
I think it's an issue with Linux. On Windows it works correctly with `mariadb-11.4.2-winx64`. I'm not sure how to fix this, WPF is not Linux friendly.

**Comment by stoneharry** [comment]
It looks like it may be possible to fix by using this library instead: https://www.nuget.org/packages/MySqlConnector/

I'll take a look into it when I get time.

**Comment by samunit** [comment]
I think I'm experiencing the same issue, was a workaround found? Using the same version as @a-l-le

**Comment by stoneharry** [comment]
Can someone test out this build and see if it resolves the issue?

https://github.com/stoneharry/WoW-Spell-Editor/pull/243#issuecomment-2322597830

Download the latest version of spell editor, then replace the executable files with the ones attached above.

**Comment by a-l-le** [comment]
Just tested, it works on the same version of mariadb

**Comment by stoneharry** [comment]
> Just tested, it works on the same version of mariadb

Thank you -- just to be clear, the original issue is resolved with this test build?

if it is, then I can work on fixing it up into a public release.

**Comment by a-l-le** [comment]
As far as I can tell. Connected to the db and populated it.
