### ISSUE TITLE
Help me please, Faile to load core DBC files based on binding!

### ISSUE THREAD

**Issue by AdemarLombriga** [stoneharry/WoW-Spell-Editor#242]
![Captura de tela 2024-08-13 134726](https://github.com/user-attachments/assets/5e23cc80-9458-49f2-ac0c-754d62621f80)

**Comment by AdemarLombriga** [comment]
[debug_output.txt](https://github.com/user-attachments/files/16602868/debug_output.txt)

**Comment by stoneharry** [comment]
```
System.InvalidCastException: Objeto não pode ser convertido de DBNull em outros tipos.
   em System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   em MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   em MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   em MySql.Data.MySqlClient.MySqlConnection.Open()
   em SpellEditor.Sources.Database.MySQL..ctor(Boolean initialiseDatabase)
   em SpellEditor.Sources.Database.AdapterFactory.GetAdapter(Boolean initialiseDatabase)
   em SpellEditor.MainWindow.<>c__DisplayClass44_0.<LoadAllData>b__1(
```

Which WoW version are you using? Which locale (can you upload your DBC files for me to look at?)

Are you using MySQL or SQLite? 

If MySQL, try using a different database name.

If SQLite, try deleting the `SpellEditor.db` file and trying again.

**Comment by AdemarLombriga** [comment]
I'm using version 3.3.5
![image](https://github.com/user-attachments/assets/a1757479-b85e-4ead-b34d-be4f8d7f1f13)

**Comment by AdemarLombriga** [comment]
[dbc.zip](https://github.com/user-attachments/files/16627907/dbc.zip)

**Comment by samunit** [comment]
Think I have the same issue, using MariaDB 1.11.6 on debian, client 3.3.5 with mysql, tried different version of the software.

`System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at SpellEditor.Sources.Database.MySQL..ctor(Boolean initialiseDatabase)
   at SpellEditor.Sources.Database.AdapterFactory.GetAdapter(Boolean initialiseDatabase)
   at SpellEditor.MainWindow.<>c__DisplayClass44_0.<loadAllData>b__0()`

**Comment by MCurcan** [comment]
I have same issue and i'm at the same point as you

**Comment by stoneharry** [comment]
For the Linux issues with MariaDB, see: https://github.com/stoneharry/WoW-Spell-Editor/issues/230#issuecomment-2256028864
